# Generated by Django 5.1.4 on 2025-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_iteea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveBigIntegerField(),
        ),
    ]
