# Generated by Django 5.1.4 on 2025-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_iteea', '0002_remove_course_date_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course_category',
            name='course',
            field=models.ManyToManyField(related_name='course', to='project_iteea.course'),
        ),
    ]
