# Generated by Django 5.1.4 on 2025-06-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_iteea', '0003_remove_course_category_course_category_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ordered_places',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
