# Generated by Django 5.1.4 on 2025-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_iteea', '0004_alter_news_ordered_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.AddField(
            model_name='news',
            name='new_email',
            field=models.ManyToManyField(related_name='new_email', to='project_iteea.news_email'),
        ),
    ]
